### PR TITLE
Klipsify "Polymorphism in Clojure: Protocols and Multimethods"

### PR DESCRIPTION
**Pull request by viebel**

### CODE REVIEW

**Comment by seancorfield** [comment]
This duplicates the link to the tutorials and cookbooks.

I'm fine with mentioning Klipse on the site home page but it's not really tied to a specific section. I'll think about this and make an update to that page, but not this PR.

I'll keep this PR open to remind me though.

**Comment by seancorfield** [comment]
Did you mean to make a separate PR for protocols and multimethods?

**Comment by viebel** [comment]
Sorry for the mess with the PRs.
I have update this PR so that it doesn't contain the mention of Klipse. Will open a separate PR for it.

**Comment by seancorfield** [comment]
I don't like introducing a new library just to avoid Java interop here. Java interop _for Clojure_ is the right approach here and should be what is documented.

I don't mind making some accommodation for ClojureScript in some places but removing Java interop examples is not acceptable.

**Comment by viebel** [comment]
I agree with you in the general case but this article is not about Java interop but about polymorphism.
That's why I think it's acceptable to use a library that supports both Clojure and ClojureScript.

**Comment by viebel** [comment]
@seancorfield If you are against it, I could open another PR without the changes related to URI. Please advise.

**Comment by seancorfield** [comment]
Sure, go ahead. In general, I don't want to complect "changing the examples" with "Klipsifying examples". I don't mind a few things added that make the existing Clojure examples work in ClojureScript/Klipse (as you did with the visibility:hidden things).

I'm also happy to have discussions about changing the content -- separately.

**Comment by viebel** [comment]
I see.
New PR in #20

**Pull request closed without merging**
