### PR TITLE
Mention klipse

### PR DESCRIPTION
**Pull request by viebel**
Mention Klipse in the home page.

### CODE REVIEW

**Comment by seancorfield** [comment]
As I said in the other PR. I'll give some thought to how Klipse gets mentioned on the home page.

**Comment by seancorfield** [comment]
I've created #19 as a reminder to myself about this.

**Comment by viebel** [comment]
Perfect.

**Comment by seancorfield** [comment]
I updated the home page, tweaked the Klipse.md formatting and made sure it's in both the source and main branches so it's easier to view on the repo.

**Comment by viebel** [comment]
Perfect. Thanks!

**Pull request closed without merging**
