### PR TITLE
Data structures cookbook - partial review

### PR DESCRIPTION
**Pull request by bobisageek**
This PR  isn't meant to be merged, but I'm hoping for maybe a skim and feedback on the content for the cookbook. It's WIP, but I figure rather than dropping a whole page, I'd ask for a review of one section and see if anything stands out as problematic.

No rush, no obligation. :)

### CODE REVIEW

**Comment by seancorfield** [comment]
This is a great start and there were a couple of suggestions in it that I hadn't considered (in over a decade of Clojure!) so, yeah, I will be happy to merge this whenever you want and can find more time to work on it! Thank you, @bobisageek !

**Comment by seancorfield** [comment]
Looking good! Only a few more sections to add, it seems!

**Comment by seancorfield** [comment]
How do you feel about a review at this point (or a merge)? I really appreciate the work you've put in on this!

**Comment by bobisageek** [comment]
Sure. I've removed the sequences header for now so that the page doesn't have an empty section, but obviously it can still be added to.

**Comment by seancorfield** [comment]
We can add a sequences section later. This is a big help, thank you!

**Comment by seancorfield** [comment]
The site has been regenerated with your new cookbook in place. Some pages have author credits on them, usually with the original author's name and email address but I think some are GH links -- would you like that added and, if so, how would you like to be recognized?

**Comment by bobisageek** [comment]
no need to worry about it for now - I'll think it over, and maybe when I add some sequence content I'll throw a little credit at the bottom if that's ok

**Comment by seancorfield** [comment]
Works for me! Thanks, again for your contributions!

**Pull request merged**
